project:
  type: website
  output-dir: docs

website:
  title: "SBSI"
  sidebar:
    style: "docked"
    search: true
    logo: Images/Logos_Icons/seal_v3.png
    title: Santa Barbara Statistics Initiative (SBSI)
    contents:
      - href: index.qmd
        text: Home
      - href: Pages/about.qmd
        text: About
      - href: Pages/officers.qmd
        text: Officers
  
  favicon: Images/Logos_Icons/bw_sbsi.png
  
  page-footer: "Site Designed by Ethan Marzban using Quarto; Logo Designed by Ethan Marzban; ©2023"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



